name: Python package

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -e .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Set up test environment
      run: |
        cp .env.example .env
        # Use dummy values for testing - never use real credentials!
        echo "DEBUG=True" >> .env
        echo "TENANT_ID=00000000-0000-0000-0000-000000000000" >> .env
        echo "CLIENT_ID=11111111-1111-1111-1111-111111111111" >> .env
        echo "CLIENT_SECRET=dummy_secret" >> .env
        echo "SITE_URL=https://example.sharepoint.com/sites/test" >> .env
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        # Run tests that don't require actual SharePoint connection
        pytest tests/ -k "not integration"
